### PR TITLE
libayatana-indicator 0.9.2

### PR DESCRIPTION
**Pull request by sayomaki**
Update formula for `libayatana-indicator` as [upstream has released 0.9.2](https://github.com/AyatanaIndicators/libayatana-indicator/releases/tag/0.9.2)

### CODE REVIEW

**Comment by sayomaki** [comment]
```
  /usr/bin/ld: /lib/x86_64-linux-gnu/libdl.so.2: undefined reference to `_dl_vsym@GLIBC_PRIVATE'
  /usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: undefined reference to `__libc_dlclose@GLIBC_PRIVATE'
  /usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: undefined reference to `__libc_current_sigrtmax_private@GLIBC_PRIVATE'
  /usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: undefined reference to `_dl_make_stack_executable@GLIBC_PRIVATE'
  /usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: undefined reference to `__libc_thread_freeres@GLIBC_PRIVATE'
  /usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: undefined reference to `__libc_siglongjmp@GLIBC_PRIVATE'
  /usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: undefined reference to `__libc_pthread_init@GLIBC_PRIVATE'
  /usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: undefined reference to `__libc_allocate_rtsig_private@GLIBC_PRIVATE'
  /usr/bin/ld: /lib/x86_64-linux-gnu/libdl.so.2: undefined reference to `_dl_addr@GLIBC_PRIVATE'
  /usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: undefined reference to `__libc_dlopen_mode@GLIBC_PRIVATE'
  /usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: undefined reference to `__libc_dlsym@GLIBC_PRIVATE'
  /usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: undefined reference to `__libc_longjmp@GLIBC_PRIVATE'
  /usr/bin/ld: /lib/x86_64-linux-gnu/libdl.so.2: undefined reference to `_dl_sym@GLIBC_PRIVATE'
  /usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: undefined reference to `__libc_current_sigrtmin_private@GLIBC_PRIVATE'
  collect2: error: ld returned 1 exit status
```

**Comment by sayomaki** [comment]
Test failure is related to issue in #11, fix by adding additional linker `rpath` flag to compiler.

**Comment by sayomaki** [comment]
Removed `glibc` `rpath` linker flags, tests should be targeted at latest ubuntu LTS release (22.04) with system provided glibc (2.35).

Test failure on initial runs was due to using outdated ubuntu runner (`ubuntu-latest` 20.04) instead of 22.04.
